<?php

/**
 * @file
 * Adds hreflang link elements to the header of each page.
 */

/**
 * Implements hook_page_build().
 */
function hreflang_page_build(&$page) {
  // Return early if site is monolingual.
  if (!drupal_multilingual()) {
    return;
  }
  // No need to add hreflang tags for 404/403 pages.
  $status = drupal_get_http_header('status');
  if ($status == '404 Not Found' || $status == '403 Forbidden') {
    return;
  }
  $path = drupal_is_front_page() ? '' : $_GET['q'];
  $links = language_negotiation_get_switch_links(LANGUAGE_TYPE_INTERFACE, $path);
  if (empty($links->links)) {
    return;
  }
  foreach ($links->links as $langcode => $link) {
    // Content translation module may unset the href attribute.
    if (!isset($link['href']) || !isset($link['attributes']['hreflang'])) {
      continue;
    }
    $link['absolute'] = TRUE;
    if (!isset($link['query'])) {
      $link['query'] = array();
    }
    $link['query'] += drupal_get_query_parameters();
    // Remove superfluous page = (float) 0 added by comment_permalink().
    if (isset($link['query']['page']) && $link['query']['page'] === 0.0) {
      unset($link['query']['page']);
    }
    $attributes = array(
      'href' => url($link['href'], $link),
      'rel' => 'alternate',
    );
    if ($langcode === language_default('language') && variable_get('hreflang_x_default', FALSE)) {
      $attributes['hreflang'] = 'x-default';
      drupal_add_html_head_link($attributes);
    }
    $attributes['hreflang'] = $link['attributes']['hreflang'];
    drupal_add_html_head_link($attributes);
  }
}

/**
 * Implements hook_language_switch_links_alter().
 */
function hreflang_language_switch_links_alter(array &$links, $type, $path) {
  foreach ($links as $langcode => &$link) {
    // Defer to other modules setting the hreflang attribute.
    if (!isset($link['attributes']) || !array_key_exists('hreflang', $link['attributes'])) {
      $link['attributes']['hreflang'] = $langcode;
    }
  }
}

/**
 * Implements hook_menu().
 */
function hreflang_menu() {
  $items['admin/config/search/hreflang'] = array(
    'title' => 'Hreflang tags',
    'description' => 'Configure hreflang tag settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hreflang_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'hreflang.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_help().
 */
function hreflang_help($path) {
  if ($path === 'admin/config/search/hreflang') {
    return theme('html_tag', array(
      'element' => array(
        '#tag' => 'p',
        '#value' => t('Hreflang module automatically adds an hreflang tag to the page for each enabled language.'),
      ),
    ));
  }
}
